apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-d
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chdomenech/test_kubernates.git'
    path: apps/ms-d
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
